# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    persons.manager:
        class: AppBundle\Services\PersonsManager
        arguments: ["@doctrine.orm.entity_manager", "@service_container"]
